In [1]:
import pandas as pd

In [26]:
tsla_df_raw = pd.read_csv('TSLASentimentAnalyzer/sentiment_data.csv')
ford_df_raw = pd.read_csv('TSLASentimentAnalyzer/Fordstock_sentiment_data.csv')

In [32]:
tsla_df_raw.shape

(5, 11)

In [36]:
tsla_df = tsla_df_raw.drop(['Unnamed: 0'], axis=1)
ford_df = ford_df_raw.drop(['Unnamed: 0'], axis=1)

In [37]:
tsla_df.head()

,timestamp,counter,close,volume,sentiment_score,close_lag1,perc_change_close,sentiment_score_lag1,perc_change_sentiment,sentiment_SMA3mo
0,2022-03-01,298908,1099.56995,40225400,0.875772,932.00000,0.179796,0.874424,0.001541,0.000000
1,2022-04-01,204020,1145.44995,45377900,0.844894,1099.56995,0.041725,0.875772,-0.035257,0.865030
2,2022-05-01,394149,952.62000,48324400,0.856333,1145.44995,-0.168344,0.844894,0.013539,0.859000
3,2022-06-01,78141,775.00000,40931000,0.858560,952.62000,-0.186454,0.856333,0.002599,0.853262
4,2022-07-01,56180,752.28998,33343700,0.851493,775.00000,-0.029303,0.858560,-0.008231,0.855462

In [38]:
ford_df.head()

,timestamp,counter,close,volume,sentiment_score,close_lag1,perc_change_close,sentiment_score_lag1,perc_change_sentiment,sentiment_SMA3mo
0,2022-02-01,388531,1.74,90500,0.858129,0.00,inf,0.890148,-0.035970,0.000000
1,2022-03-01,596183,1.75,83500,0.864426,1.74,0.005747,0.858129,0.007338,0.870901
2,2022-04-01,121680,1.92,79700,0.867256,1.75,0.097143,0.864426,0.003274,0.863270
3,2022-05-01,148176,1.63,8700,0.884760,1.92,-0.151042,0.867256,0.020183,0.872147
4,2022-06-01,56784,1.62,9600,0.876936,1.63,-0.006135,0.884760,-0.008843,0.876317

In [39]:
tsla_df['stock_ticker'] = "TSLA"
ford_df['stock_ticker'] = "FORD"

In [40]:
print(tsla_df.shape,
ford_df.shape)

(5, 11) (6, 11)

In [42]:
tsla_df

,timestamp,counter,close,volume,sentiment_score,close_lag1,perc_change_close,sentiment_score_lag1,perc_change_sentiment,sentiment_SMA3mo,stock_ticker
0,2022-03-01,298908,1099.56995,40225400,0.875772,932.00000,0.179796,0.874424,0.001541,0.000000,TSLA
1,2022-04-01,204020,1145.44995,45377900,0.844894,1099.56995,0.041725,0.875772,-0.035257,0.865030,TSLA
2,2022-05-01,394149,952.62000,48324400,0.856333,1145.44995,-0.168344,0.844894,0.013539,0.859000,TSLA
3,2022-06-01,78141,775.00000,40931000,0.858560,952.62000,-0.186454,0.856333,0.002599,0.853262,TSLA
4,2022-07-01,56180,752.28998,33343700,0.851493,775.00000,-0.029303,0.858560,-0.008231,0.855462,TSLA

In [45]:
df_stock_sentiment_data = pd.concat([tsla_df, ford_df])

In [46]:
df_stock_sentiment_data.to_csv("final_sentiment_data.csv")